import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/styles.css',
                    'resources/js/application.js',
                    'resources/js/libs/bootstrap.min.js',
                    'resources/js/libs/jquery-1.11.0.js',
                    'resources/js/libs/bootstrap-switch.min.js',
                    'resources/js/libs/jquery.tablesorter.js',
                    'resources/fonts/glyphicons-halflings-regular.woff',
                    'resources/css/ckeditor/imageresize.css',
                    'resources/css/ckeditor/imagestyle.css',
                    'resources/css/ckeditor/ckeditor-fix.css',
                    'resources/js/libs/jquery-ui-1.10.4.js',
                    'resources/js/libs/angular-1.2.15.min.js',
                    'resources/js/libs/angular-ui-0.4.0.js',
                    'resources/js/logs-angular.ts',
                    'resources/js/absences.js',
                    'resources/js/edit-album.js',
                    'resources/js/edit-links.js',
                    'resources/js/edit-registration.js',
                    'resources/js/editable-text.js',
                    'resources/js/payment-angular.js',
                    'resources/js/accounting-angular.js',
                    'resources/js/edit-calendar.js',
                    'resources/js/edit-members.js',
                    'resources/js/edit-reregistration.js',
                    'resources/js/guest-book.js',
                    'resources/js/photos.js',
                    'resources/js/application.js',
                    'resources/js/edit-change-section.js',
                    'resources/js/edit-news.js',
                    'resources/js/edit-sections.js',
                    'resources/js/health-card.js',
                    'resources/js/registration-form.js',
                    'resources/js/attendance-angular.js',
                    'resources/js/edit-desk-listing.js',
                    'resources/js/edit-pages.js',
                    'resources/js/edit-subscription-fee.js',
                    'resources/js/leader-corner.js',
                    'resources/js/reorder-list.js',
                    'resources/js/edit-documents.js',
                    'resources/js/edit-parameters.js',
                    'resources/js/edit-suggestions.js',
                    'resources/js/send-section-email.js',
                    'resources/js/ckeditor.js',
                    'resources/js/edit-emails.js',
                    'resources/js/edit-photos.js',
                    'resources/js/edit-users.js',
                    'resources/js/listing-subgroups.js',
                    'resources/js/edit-absences.js',
                    'resources/js/edit-leaders.js',
                    'resources/js/edit-privileges.js',
                    'resources/js/edit-year-in-section.js',
                    'resources/js/ckeditor/ckeditor.js',
                    'resources/css/bootstrap-colorpicker.min.css',
                    'resources/js/libs/bootstrap-colorpicker.min.js',
                   ],
            refresh: true,
        }),
    ],
    resolve: {
        alias: {
            jquery: 'jquery',
        },
    },
    define: {
        'window.jQuery': 'jquery',
        'window.$': 'jquery',
    },
});
